payments:
  secret-key: test_sk_dummy
  receipt:
    base-url: https://pay.local/receipts

server:
  port: 9090

logging:
  level:
    root: INFO


spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration


